In [114]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,mean_squared_error
from sklearn.linear_model import LogisticRegression

In [115]:
df = pd.read_csv("data_updated_1.csv",low_memory=False)

In [116]:
df.head()

loan_amnt  term  int_rate  installment emp_length  annual_inc  loan_status  \
0       5000    36     10.65       162.87  10+ years     24000.0   Fully Paid   
1       2500    60     15.27        59.83   < 1 year     30000.0  Charged Off   
2       2400    36     15.96        84.33  10+ years     12252.0   Fully Paid   
3      10000    36     13.49       339.31  10+ years     49200.0   Fully Paid   
4       3000    60     12.69        67.79     1 year     80000.0      Current   

   pub_rec revol_util  total_acc   total_pymnt  total_rec_late_fee  \
0      0.0      83.7%        9.0   5863.155187                0.00   
1      0.0       9.4%        4.0   1008.710000                0.00   
2      0.0      98.5%       10.0   3005.666844                0.00   
3      0.0        21%       37.0  12231.890000               16.97   
4      0.0      53.9%       38.0   3784.490000                0.00   

   pub_rec_bankruptcies  last_pymnt_month  last_pymnt_year  issue_year  \
0                   0.0               1.0           2015.0        2011   
1                   0.0               4.0           2013.0        2011   
2                   0.0               6.0           2014.0        2011   
3                   0.0               1.0           2015.0        2011   
4                   0.0               9.0           2016.0        2011   

   issue_month  
0           12  
1           12  
2           12  
3           12  
4           12

In [117]:
df["loan_status"].value_counts()

Fully Paid                                             33586
Charged Off                                             5653
Does not meet the credit policy. Status:Fully Paid      1988
Does not meet the credit policy. Status:Charged Off      761
Current                                                  513
In Grace Period                                           16
Late (31-120 days)                                        12
Late (16-30 days)                                          5
Default                                                    1
Name: loan_status, dtype: int64

fully paid ,current,grace period,16 - 30 days late chalega
else nahi chalega

In [118]:
df_copy = df.copy()

In [119]:
le = LabelEncoder()

In [120]:
df_copy["emp_length_en"] = le.fit_transform(df_copy["emp_length"])

In [121]:
df_copy.head()

loan_amnt  term  int_rate  installment emp_length  annual_inc  loan_status  \
0       5000    36     10.65       162.87  10+ years     24000.0   Fully Paid   
1       2500    60     15.27        59.83   < 1 year     30000.0  Charged Off   
2       2400    36     15.96        84.33  10+ years     12252.0   Fully Paid   
3      10000    36     13.49       339.31  10+ years     49200.0   Fully Paid   
4       3000    60     12.69        67.79     1 year     80000.0      Current   

   pub_rec revol_util  total_acc   total_pymnt  total_rec_late_fee  \
0      0.0      83.7%        9.0   5863.155187                0.00   
1      0.0       9.4%        4.0   1008.710000                0.00   
2      0.0      98.5%       10.0   3005.666844                0.00   
3      0.0        21%       37.0  12231.890000               16.97   
4      0.0      53.9%       38.0   3784.490000                0.00   

   pub_rec_bankruptcies  last_pymnt_month  last_pymnt_year  issue_year  \
0                   0.0               1.0           2015.0        2011   
1                   0.0               4.0           2013.0        2011   
2                   0.0               6.0           2014.0        2011   
3                   0.0               1.0           2015.0        2011   
4                   0.0               9.0           2016.0        2011   

   issue_month  emp_length_en  
0           12              1  
1           12             10  
2           12              1  
3           12              1  
4           12              0

In [122]:
df_copy["emp_length_en"].value_counts()

1     9369
10    5062
2     4743
3     4364
4     3649
0     3595
5     3458
6     2375
7     1875
8     1592
9     1341
11    1112
Name: emp_length_en, dtype: int64

In [123]:
df_copy[df_copy["loan_status"] == "Default"]

loan_amnt  term  int_rate  installment emp_length  annual_inc  \
20645      16000    60      16.4        392.5     1 year     70000.0   

      loan_status  pub_rec revol_util  total_acc  total_pymnt  \
20645     Default      1.0      40.1%       18.0     23126.44   

       total_rec_late_fee  pub_rec_bankruptcies  last_pymnt_month  \
20645                 0.0                   1.0               1.0   

       last_pymnt_year  issue_year  issue_month  emp_length_en  
20645           2016.0        2011            2              0

In [124]:
df_copy = df_copy.drop(20645)

In [125]:
df_copy = df_copy[df_copy["loan_status"].isin(["Fully Paid","Charged Off"])]

In [126]:
df_copy['loan_status'].value_counts()

Fully Paid     33586
Charged Off     5653
Name: loan_status, dtype: int64

In [127]:
df_copy["loan_status_en"] = le.fit_transform(df_copy["loan_status"])

In [128]:
df_copy["loan_status_en"].value_counts()

1    33586
0     5653
Name: loan_status_en, dtype: int64

In [129]:
df_copy[["loan_status_en","loan_status"]].head()

loan_status_en  loan_status
0               1   Fully Paid
1               0  Charged Off
2               1   Fully Paid
3               1   Fully Paid
5               1   Fully Paid

In [130]:
df_copy.shape

(39239, 19)

In [131]:
df_copy.head()

loan_amnt  term  int_rate  installment emp_length  annual_inc  loan_status  \
0       5000    36     10.65       162.87  10+ years     24000.0   Fully Paid   
1       2500    60     15.27        59.83   < 1 year     30000.0  Charged Off   
2       2400    36     15.96        84.33  10+ years     12252.0   Fully Paid   
3      10000    36     13.49       339.31  10+ years     49200.0   Fully Paid   
5       5000    36      7.90       156.46    3 years     36000.0   Fully Paid   

   pub_rec revol_util  total_acc   total_pymnt  total_rec_late_fee  \
0      0.0      83.7%        9.0   5863.155187                0.00   
1      0.0       9.4%        4.0   1008.710000                0.00   
2      0.0      98.5%       10.0   3005.666844                0.00   
3      0.0        21%       37.0  12231.890000               16.97   
5      0.0      28.3%       12.0   5632.210000                0.00   

   pub_rec_bankruptcies  last_pymnt_month  last_pymnt_year  issue_year  \
0                   0.0               1.0           2015.0        2011   
1                   0.0               4.0           2013.0        2011   
2                   0.0               6.0           2014.0        2011   
3                   0.0               1.0           2015.0        2011   
5                   0.0               1.0           2015.0        2011   

   issue_month  emp_length_en  loan_status_en  
0           12              1               1  
1           12             10               0  
2           12              1               1  
3           12              1               1  
5           12              3               1

In [132]:
for col in df_copy.columns:
    print(col,df_copy[col].isnull().sum())

loan_amnt 0
term 0
int_rate 0
installment 0
emp_length 1057
annual_inc 0
loan_status 0
pub_rec 0
revol_util 50
total_acc 0
total_pymnt 0
total_rec_late_fee 0
pub_rec_bankruptcies 697
last_pymnt_month 71
last_pymnt_year 71
issue_year 0
issue_month 0
emp_length_en 0
loan_status_en 0


In [133]:
df_copy = df_copy[df_copy['emp_length'].notna()]

In [134]:
df_copy = df_copy[df_copy['annual_inc'].notna()]

In [135]:
df_copy["annual_inc"].isnull().sum()

0

In [136]:
df_copy = df_copy[df_copy['last_pymnt_year'].notna()]

In [137]:
def update_revol_unit(value):
    return eval(value.replace("%","").replace(" ","")) 

In [138]:
df_revol_util = df_copy["revol_util"].copy()
df_revol_util = df_revol_util.fillna("0")
new_revol_util = map(update_revol_unit,df_revol_util)
new_revol_util = list(new_revol_util)
df_copy["revol_util"] = pd.Series(new_revol_util)
df_copy["revol_util"].head()

0    83.7
1     9.4
2    98.5
3    21.0
5    85.6
Name: revol_util, dtype: float64

In [139]:
df_copy["revol_util"].isnull().sum()

1670

In [140]:
def replace_na(col_name,value=0):
    df_copy[col_name] = df_copy[col_name].fillna(0)

In [141]:
replace_na(col_name = "pub_rec")
replace_na(col_name = "revol_util")
replace_na(col_name = "total_acc")
replace_na(col_name = "pub_rec_bankruptcies")

In [142]:
for col in df_copy.columns:
    print(col,df_copy[col].isnull().sum())

loan_amnt 0
term 0
int_rate 0
installment 0
emp_length 0
annual_inc 0
loan_status 0
pub_rec 0
revol_util 0
total_acc 0
total_pymnt 0
total_rec_late_fee 0
pub_rec_bankruptcies 0
last_pymnt_month 0
last_pymnt_year 0
issue_year 0
issue_month 0
emp_length_en 0
loan_status_en 0


In [143]:
df_copy["revol_util"]

0        83.7
1         9.4
2        98.5
3        21.0
5        85.6
         ... 
39781     0.0
39782     0.0
39783     0.0
39784     0.0
39785     0.0
Name: revol_util, Length: 38116, dtype: float64

In [144]:
df_copy.shape

(38116, 19)

In [145]:
df_copy = df_copy.drop(labels="emp_length",axis=1)

In [146]:
df_copy = df_copy.drop(labels="loan_status",axis=1)

In [147]:
df_copy.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'annual_inc', 'pub_rec',
       'revol_util', 'total_acc', 'total_pymnt', 'total_rec_late_fee',
       'pub_rec_bankruptcies', 'last_pymnt_month', 'last_pymnt_year',
       'issue_year', 'issue_month', 'emp_length_en', 'loan_status_en'],
      dtype='object')

In [148]:
x = df_copy[[col_name for col_name in df_copy.columns if col_name not in  ["loan_status_en","pub_rec"]]]
y = df_copy["loan_status_en"]

In [149]:
x

loan_amnt  term  int_rate  installment  annual_inc  revol_util  \
0           5000    36     10.65       162.87     24000.0        83.7   
1           2500    60     15.27        59.83     30000.0         9.4   
2           2400    36     15.96        84.33     12252.0        98.5   
3          10000    36     13.49       339.31     49200.0        21.0   
5           5000    36      7.90       156.46     36000.0        85.6   
...          ...   ...       ...          ...         ...         ...   
39781       2500    36      8.07        78.42    110000.0         0.0   
39782       8500    36     10.28       275.38     18000.0         0.0   
39783       5000    36      8.07       156.84    100000.0         0.0   
39784       5000    36      7.43       155.38    200000.0         0.0   
39785       7500    36     13.75       255.43     22000.0         0.0   

       total_acc   total_pymnt  total_rec_late_fee  pub_rec_bankruptcies  \
0            9.0   5863.155187                0.00                   0.0   
1            4.0   1008.710000                0.00                   0.0   
2           10.0   3005.666844                0.00                   0.0   
3           37.0  12231.890000               16.97                   0.0   
5           12.0   5632.210000                0.00                   0.0   
...          ...           ...                 ...                   ...   
39781       40.0   2822.969293                0.00                   0.0   
39782        9.0   9913.491822                0.00                   0.0   
39783       20.0   5272.161128                0.00                   0.0   
39784       26.0   5174.198551                0.00                   0.0   
39785        8.0   9195.263334                0.00                   0.0   

       last_pymnt_month  last_pymnt_year  issue_year  issue_month  \
0                   1.0           2015.0        2011           12   
1                   4.0           2013.0        2011           12   
2                   6.0           2014.0        2011           12   
3                   1.0           2015.0        2011           12   
5                   1.0           2015.0        2011           12   
...                 ...              ...         ...          ...   
39781               7.0           2010.0        2007            7   
39782               7.0           2010.0        2007            7   
39783               4.0           2008.0        2007            7   
39784               1.0           2008.0        2007            7   
39785               6.0           2010.0        2007            6   

       emp_length_en  
0                  1  
1                 10  
2                  1  
3                  1  
5                  3  
...              ...  
39781              4  
39782              3  
39783             10  
39784             10  
39785             10  

[38116 rows x 15 columns]

In [150]:
y

0        1
1        0
2        1
3        1
5        1
        ..
39781    1
39782    1
39783    1
39784    1
39785    1
Name: loan_status_en, Length: 38116, dtype: int64

Train test splitting

In [151]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=100)

In [152]:
print("x : ",x_train.shape,x_test.shape)
print("y : ",y_train.shape,y_test.shape)

x :  (26681, 15) (11435, 15)
y :  (26681,) (11435,)


In [153]:
dtr1 = DecisionTreeClassifier(criterion = "gini")

In [154]:
dtr2 = DecisionTreeClassifier(criterion = "entropy")

In [155]:
dtr1.fit(x_train,y_train)

DecisionTreeClassifier()

In [156]:
dtr2.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [157]:
predictions1 = dtr1.predict(x_test)

In [158]:
predictions2 = dtr2.predict(x_test)

In [159]:
cm_dtr1 = confusion_matrix(y_test,predictions1)

In [160]:
cm_dtr2 = confusion_matrix(y_test,predictions2)

In [161]:
cm_dtr1

array([[1374,  165],
       [ 226, 9670]])

In [162]:
cm_dtr2

array([[1397,  142],
       [ 176, 9720]])

In [163]:
dtr1.predict([[5000,36,10.65,162.87,24000.0,83.7,9.0,5863.155187,0.00,0.0,1.0,2015.0,2011,12,1]])

/home/chinmay/study/lending_club_analysis/envr/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [164]:
mean_squared_error(y_test,predictions1)

0.03419326628771316

In [165]:
mean_squared_error(y_test,predictions2)

0.02780935723655444

In [166]:
dtr1.score(x_test,y_test) * 100

96.58067337122868

In [189]:
print("Test accuracy : ")
print("Gini : ",dtr1.score(x_test,y_test) * 100)
print("Entropy : ", dtr2.score(x_test,y_test) * 100)

Test accuracy : 
Gini :  96.58067337122868
Entropy :  97.21906427634455


In [168]:
rf1 = RandomForestClassifier(criterion = "gini")
rf2 = RandomForestClassifier(criterion = "entropy")

In [169]:
rf1.fit(x_train,y_train)

RandomForestClassifier()

In [170]:
rf2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

In [171]:
predictions_rf1 = rf1.predict(x_test)

In [172]:
predictions_rf2 = rf2.predict(x_test)

In [173]:
cm_rf1 = confusion_matrix(y_test,predictions_rf1)
cm_rf2 = confusion_matrix(y_test,predictions_rf2)

In [174]:
cm_rf1

array([[1172,  367],
       [  10, 9886]])

In [175]:
cm_rf2

array([[1196,  343],
       [  10, 9886]])

In [176]:
mean_squared_error(y_test,predictions_rf1)

0.032968954962833405

In [177]:
mean_squared_error(y_test,predictions_rf2)

0.030870135548753827

In [178]:
rf1.score(x_test,y_test) *100

96.70310450371666

In [179]:
rf2.score(x_test,y_test) * 100

96.91298644512462

In [180]:
logr = LogisticRegression()

In [181]:
logr.fit(x_train,y_train)

/home/chinmay/study/lending_club_analysis/envr/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [182]:
preditions_logr = logr.predict(x_test)

In [183]:
preditions_logr

array([1, 0, 0, ..., 0, 1, 1])

In [184]:
cm_logr = confusion_matrix(y_test,preditions_logr)

In [185]:
cm_logr

array([[1149,  390],
       [  62, 9834]])

In [186]:
mean_squared_error(y_test,preditions_logr,squared=False)

0.19881590890024897

In [187]:
logr.score(x_test,y_test) * 100

96.0472234368168